import { generatePath } from "react-router-dom";
import { ROUTES, WELLNESS_SESSION_KIND } from "./routes";

/**
 * In-app search index — aligned with Flutter `AppSearchController._buildIndex` (titles, keywords, targets).
 * `to` is passed to `navigate()`.
 */
export type HomeSearchAction = {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  keywords: readonly string[];
  to: string;
};

export const HOME_SEARCH_ACTIONS: readonly HomeSearchAction[] = [
  {
    id: "consultation",
    title: "Book Consultation",
    subtitle: "Consult with a doctor at hospital or virtually",
    category: "Services",
    keywords: [
      "consultation",
      "doctor",
      "consult",
      "physician",
      "opd",
      "hospital",
      "virtual",
      "appointment",
    ],
    to: ROUTES.consultationType,
  },
  {
    id: "health-checkups",
    title: "Health Checkups",
    subtitle: "Book free health checkups",
    category: "Services",
    keywords: [
      "health checkup",
      "checkup",
      "diagnostics",
      "annual checkup",
      "full body",
      "screening",
    ],
    to: generatePath(ROUTES.diagnosticsType, { type: "health-checkups" }),
  },
  {
    id: "lab-tests",
    title: "Lab Tests",
    subtitle: "Book diagnostic lab tests",
    category: "Services",
    keywords: [
      "lab test",
      "lab",
      "blood test",
      "cbc",
      "thyroid",
      "sugar",
      "cholesterol",
      "urine",
      "diagnostics",
    ],
    to: generatePath(ROUTES.diagnosticsType, { type: "lab-tests" }),
  },
  {
    id: "pharmacy",
    title: "Order Medicines",
    subtitle: "Get medicines delivered to your door",
    category: "Services",
    keywords: [
      "pharmacy",
      "medicine",
      "tablet",
      "drug",
      "capsule",
      "syrup",
      "paracetamol",
      "order medicine",
      "prescription",
    ],
    to: ROUTES.pharmacy,
  },
  {
    id: "dental",
    title: "Dental Services",
    subtitle: "Book dental checkup or treatment",
    category: "Services",
    keywords: ["dental", "dentist", "teeth", "tooth", "cavity", "cleaning", "braces", "root canal", "oral"],
    to: ROUTES.dentalSelectPeople,
  },
  {
    id: "vision",
    title: "Vision Services",
    subtitle: "Eye checkup or glasses/lens",
    category: "Services",
    keywords: [
      "vision",
      "eye",
      "glasses",
      "lens",
      "contact lens",
      "optician",
      "lenskart",
      "spectacles",
      "sight",
    ],
    to: ROUTES.vision,
  },
  {
    id: "vaccination",
    title: "Vaccination",
    subtitle: "Book vaccination appointments",
    category: "Services",
    keywords: ["vaccine", "vaccination", "immunization", "flu", "hepatitis", "covid", "shot", "booster"],
    to: ROUTES.vaccinationSelectPeople,
  },
  {
    id: "gym",
    title: "Gym Membership",
    subtitle: "Explore gym membership plans",
    category: "Services",
    keywords: ["gym", "fitness", "workout", "cult", "membership", "exercise", "training", "cult fit"],
    to: ROUTES.gymMembership,
  },
  {
    id: "mental-wellness",
    title: "Mental Wellness",
    subtitle: "Counselling and wellness sessions",
    category: "Services",
    keywords: [
      "mental",
      "wellness",
      "counselling",
      "therapy",
      "stress",
      "anxiety",
      "depression",
      "psychologist",
      "mental health",
    ],
    to: generatePath(ROUTES.servicesWellness, { wellnessKind: WELLNESS_SESSION_KIND.mentalWellness }),
  },
  {
    id: "nutrition",
    title: "Nutrition",
    subtitle: "Diet consultation and nutrition plans",
    category: "Health",
    keywords: [
      "nutrition",
      "diet",
      "dietician",
      "weight loss",
      "meal plan",
      "calories",
      "protein",
      "food",
    ],
    to: generatePath(ROUTES.servicesWellness, { wellnessKind: WELLNESS_SESSION_KIND.nutrition }),
  },
  {
    id: "wallet",
    title: "OPD Wallet",
    subtitle: "Check balance, transactions & recharge",
    category: "Account",
    keywords: ["wallet", "balance", "recharge", "opd", "payment", "money", "transaction", "pay"],
    to: ROUTES.wallet,
  },
  {
    id: "claims",
    title: "OPD Claims",
    subtitle: "Submit and track your claims",
    category: "Account",
    keywords: ["claim", "claims", "reimbursement", "opd claim", "submit claim", "insurance"],
    to: ROUTES.claims,
  },
  {
    id: "bank",
    title: "Bank Details",
    subtitle: "Manage your bank accounts",
    category: "Account",
    keywords: ["bank", "bank details", "account", "ifsc", "upi", "bank account"],
    to: ROUTES.profileBank,
  },
  {
    id: "orders",
    title: "My Orders",
    subtitle: "Track and manage your orders",
    category: "Account",
    keywords: ["orders", "order", "track", "order status", "my orders", "delivery"],
    to: ROUTES.orders,
  },
  {
    id: "health-score",
    title: "Health Score",
    subtitle: "View BMI and health information on your profile",
    category: "Health",
    keywords: ["health score", "bmi", "body mass index", "weight", "height", "fitness score"],
    to: ROUTES.profile,
  },
  {
    id: "help",
    title: "Help & Support",
    subtitle: "Raise tickets and get help",
    category: "Support",
    keywords: ["help", "support", "ticket", "issue", "complaint", "contact", "problem", "query"],
    to: ROUTES.servicesHelpTab,
  },
  {
    id: "faq",
    title: "FAQ",
    subtitle: "Frequently asked questions",
    category: "Support",
    keywords: ["faq", "frequently asked", "question", "how to", "guide"],
    to: ROUTES.servicesHelpTab,
  },
  {
    id: "chronic",
    title: "Chronic Care",
    subtitle: "Manage chronic conditions",
    category: "Services",
    keywords: [
      "chronic",
      "diabetes",
      "bp",
      "blood pressure",
      "hypertension",
      "sugar",
      "chronic care",
      "management",
    ],
    to: ROUTES.services,
  },
  {
    id: "address",
    title: "Add Address",
    subtitle: "Add or manage delivery addresses",
    category: "Account",
    keywords: ["address", "delivery address", "location", "add address", "pincode"],
    to: ROUTES.profileAddressAdd,
  },
];
