/** Application route paths — single source of truth for navigation (OCP: extend here). */
export const ROUTES = {
  /** Onboarding carousel; use `login` for the auth screen. */
  root: "/",
  login: "/login",
  otp: "/otp",
  dashboard: "/dashboard",
  profile: "/profile",
  profileBank: "/profile/bank",
  profileBankAdd: "/profile/bank/add",
  profileBankView: "/profile/bank/view/:bankId",
  profileBankEdit: "/profile/bank/edit/:bankId",
  profileAddress: "/profile/address",
  profileAddressAdd: "/profile/address/add",
  profileAddressEdit: "/profile/address/edit/:addressId",
  profileMembers: "/profile/members",
  /** Single add-member flow; legacy `/Diagnostics/.../add-family-member` URLs redirect here. */
  profileMembersAdd: "/profile/members/add",
  profileMembersEdit: "/profile/members/edit/:memberId",
  profileSubscriptions: "/profile/subscriptions",
  services: "/services",
  diagnosticsType: "/Diagnostics/:type",
  diagnosticsAddFamilyMember: "/Diagnostics/:type/add-family-member",
  diagnosticsPlan: "/Diagnostics/:type/plan",
  diagnosticsVendors: "/Diagnostics/:type/vendors",
  diagnosticsSlots: "/Diagnostics/:type/slots",
  diagnosticsOverview: "/Diagnostics/:type/overview",
  diagnosticsBookingSuccess: "/Diagnostics/:type/booking-success",
  consultation: "/consultation/:type",
  consultationAddFamilyMember: "/consultation/:type/add-family-member",
  consultationSpecialties: "/consultation/:type/specialties",
  consultationHospitalResults: "/consultation/at_hospital/specialties/:specialtyId",
  consultationHospitalSlots: "/consultation/at_hospital/specialties/:specialtyId/appointment/:doctorId",
  consultationHospitalOverview: "/consultation/at_hospital/specialties/:specialtyId/appointment/:doctorId/overview",
  dental: "/dental",
  vision: "/vision",
  pharmacy: "/pharmacy",
  orders: "/orders",
  help: "/help",
  gymMembership: "services/gym-membership",
  gymMembershipSelectPeople: "services/gym-membership/select-people",
  gymMembershipConfigure: "services/gym-membership/configure",
  gymMembershipOverview: "services/gym-membership/overview",
  gymMembershipSelectClinic: "services/gym-membership/select-clinic",
  cartOverview: "/cart-overview",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
