name: Local Auto Deploy

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run Deploy Script
        shell: cmd
        run: D:\deploy.bat